name: at
description: 42 Ecole related tools
version: 0.0.1

environment:
  sdk: ^3.1.5

dependencies:
  equatable: ^2.0.5
  meta: ^1.11.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.1.0
